[package]
name = "bevy_ascii"
version = "0.1.0"
authors = ["mcparland"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
crossterm = "0.18.0"